NEOS-crazy-people/neos-project

src/main/java/com/example/neosproject/controller/fix/FixController.java, src/main/resources/static/css/fix/header.css, src/main/resources/static/css/fix/loginHeader.css, src/main/resources/static/css/search/searchComplete.css, src/main/resources/static/js/fix/login.js, src/main/resources/static/js/search/searchComplete.js, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/fix/loginHeader.html, src/main/resources/templates/app/main/loginMain.html, src/main/resources/templates/app/main/main.html, src/main/resources/templates/app/search/searchAfter.html, src/main/resources/templates/app/search/searchBefore.html, src/main/resources/templates/app/search/searchComplete.html
=> 조성현 - 메인페이지 수정 / 헤더 js 수정 완료

src/main/java/com/example/neosproject/controller/admin/AdminController.java, src/main/resources/static/css/admin/adminTotalCss.css, src/main/resources/static/css/admin/contentManagement.css, src/main/resources/static/css/admin/noticePost.css, src/main/resources/static/css/community/board.css, src/main/resources/templates/app/admin/adminIndex.html, src/main/resources/templates/app/admin/adminNavBar.html, src/main/resources/templates/app/admin/base.html, src/main/resources/templates/app/admin/configBanner.html, src/main/resources/templates/app/admin/noticePost.html, src/main/resources/templates/app/admin/studyManagement.html, src/main/resources/templates/app/community/counseling.html, src/main/resources/templates/app/community/freeboard.html
박종우 관리자 페이지 11.15 ver 1 (임시 커밋)
=> 박종우 관리자 페이지 11.15 ver 1 (임시 커밋)

src/main/java/com/example/neosproject/controller/admin/AdminController.java, src/main/resources/static/css/community/board.css, src/main/resources/static/css/community/board1.css, src/main/resources/static/css/community/board2.css, src/main/resources/static/css/community/board3.css, src/main/resources/static/js/community/freeboard.js, src/main/resources/templates/app/admin/adminNavBar.html, src/main/resources/templates/app/admin/counselingBoardManagement.html, src/main/resources/templates/app/admin/freeBoardManagement.html, src/main/resources/templates/app/community/counseling.html, src/main/resources/templates/app/community/freeboard.html
관리자 페이지
메뉴바 컨텐츠 관리 부분 수정
관리자 로고부분 흰색 배경 수정
커뮤니티 게시판 글 작성 버튼 추가
=> 공지사항 관리, 스터디 게시물 관리, 고민 게시판 게시물 관리, 자유 게시판 게시물 관리

src/main/java/com/example/neosproject/controller/neosUser/NeosUserController.java, src/main/resources/static/css/fix/chatting.css, src/main/resources/static/css/neosUser/userInfo.css, src/main/resources/static/js/neosUser/userInfo2.js, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/fix/chattingBase.html, src/main/resources/templates/app/neosUser/neosListAfter.html, src/main/resources/templates/app/neosUser/neosListBefore.html, src/main/resources/templates/app/neosUser/userInfo2.html
류호근 프로필 상세보기 스터디 초대 클릭 시 모달창 관련 작업 완료
=> 류호근 프로필 상세보기 스터디 초대 클릭 시 모달창 관련 작업 완료

src/main/resources/static/css/study/studyManagement.css, src/main/resources/templates/app/study/studyManagement.html, src/main/resources/templates/app/study/test.html
=> [추성윤] 스터디 상세_정보관리 페이지 완료

src/main/resources/static/css/fix/chatting.css, src/main/resources/static/css/neosUser/userInfo.css, src/main/resources/templates/app/fix/chattingBase.html, src/main/resources/templates/app/neosUser/userInfo.html
=> 류호근 프로필 상세보기 스터디 초대 모달 오류 수정

src/main/java/com/example/neosproject/controller/admin/AdminController.java, src/main/resources/static/css/admin/adminPaging.css, src/main/resources/static/css/admin/inquiryList.css, src/main/resources/static/js/community/freeboard.js, src/main/resources/templates/app/admin/adminIndex.html, src/main/resources/templates/app/admin/adminNavBar.html, src/main/resources/templates/app/admin/adminPaging.html, src/main/resources/templates/app/admin/bannerEdit.html, src/main/resources/templates/app/admin/configBanner.html, src/main/resources/templates/app/admin/counselingBoardManagement.html, src/main/resources/templates/app/admin/inquiryList.html, src/main/resources/templates/app/admin/noticePost.html, src/main/resources/templates/app/admin/studyManagement.html, src/main/resources/templates/app/community/counseling.html, src/main/resources/templates/app/community/freeboard.html
=> 박종우 11/16 임시커밋

src/main/resources/static/css/search/searchAfter.css, src/main/resources/static/css/search/searchBefore.css, src/main/resources/templates/app/fix/loginHeader.html, src/main/resources/templates/app/main/main.html, src/main/resources/templates/app/search/searchAfter.html, src/main/resources/templates/app/search/searchBefore.html, src/main/resources/templates/app/search/searchComplete.html
조성현 - 검색창 초기화 완료 / 내 정보 문구 수정 완료
js 적용 완료
=> 조성현 - 검색창 초기화 완료 / 내 정보 문구 수정 완료

src/main/resources/static/css/fix/chatting.css, src/main/resources/static/js/fix/chatting.js, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/fix/chattingBase.html, src/main/resources/templates/app/neosUser/neosListAfter.html, src/main/resources/templates/app/neosUser/neosListBefore.html, src/main/resources/templates/app/neosUser/userInfo.html, src/main/resources/templates/app/neosUser/userInfo2.html, src/main/resources/templates/app/neosUser/userInfoAllNo.html
류호근 모든 화면에 fix 되어있는 채팅창 모달 작업 시작
=> 류호근 모든 화면에 fix 되어있는 채팅창 모달 작업 시작

src/main/java/com/example/neosproject/controller/study/StudyController.java, src/main/resources/static/css/study/listStudy.css, src/main/resources/static/css/study/workStudy.css, src/main/resources/static/js/study/studyManagement.js, src/main/resources/templates/app/study/baseStudy.html, src/main/resources/templates/app/study/createStudy.html, src/main/resources/templates/app/study/detailStudy.html, src/main/resources/templates/app/study/feedStudy.html, src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/app/study/questionStudy.html, src/main/resources/templates/app/study/studyManagement.html, src/main/resources/templates/app/study/workStudy.html
[추성윤] 전체 페이지 파비콘 추가 / 스터디 상세 : 일감_할일관리 CSS 완료 / 관리탭 일부 JS 적용
=> [추성윤] 전체 페이지 파비콘 추가 / 스터디 상세 : 일감_할일관리 CSS 완료 / 관리탭 일부 JS 적용

src/main/java/com/example/neosproject/controller/myPage/MyPageController.java, src/main/java/com/example/neosproject/controller/store/StoreController.java, src/main/resources/static/css/myPage/myPage.css, src/main/resources/static/css/myPage/myPageAlarm.css, src/main/resources/static/css/myPage/myPageFavorite.css, src/main/resources/static/css/myPage/myPageStudy.css, src/main/resources/static/css/store/storeCreate.css, src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/app/myPage/myPage.html, src/main/resources/templates/app/myPage/myPageAlarm.html, src/main/resources/templates/app/myPage/myPageFavorite.html, src/main/resources/templates/app/myPage/myPageNeos.html, src/main/resources/templates/app/myPage/myPageStore.html, src/main/resources/templates/app/myPage/myPageStudy.html, src/main/resources/templates/app/store/storeCreate.html, src/main/resources/templates/app/store/storeDetail.html, src/main/resources/templates/app/store/storeList.html
김로사 마이페이지 탭메뉴 이동가능(정보 페이지, 작은 탭 작업중)
=> 김로사 마이페이지 탭메뉴 이동가능(정보 페이지, 작은 탭 작업중)

src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/app/myPage/myPage.html
=> 김로사 마이페이지 탭메뉴 이동 완료(정보 페이지X)

src/main/resources/static/css/inquiry/inquiry.css, src/main/resources/static/css/inquiry/inquiryReply.css, src/main/resources/static/js/inquiry/Inquery.js, src/main/resources/templates/app/inquiry/inquiry.html, src/main/resources/templates/app/inquiry/inquiryReply.html, src/main/resources/templates/app/loginAndJoin/edragonClause.html, src/main/resources/templates/app/loginAndJoin/electronicFinanceClause.html, src/main/resources/templates/app/loginAndJoin/individualClause.html, src/main/resources/templates/app/loginAndJoin/join.html, src/main/resources/templates/app/loginAndJoin/joinPage.html, src/main/resources/templates/app/loginAndJoin/login.html, src/main/resources/templates/app/notice/notice.html, src/main/resources/templates/app/notice/noticeDetails.html
심민성  / 문의하기 , 문의하기 답변  textarea  수정 완료
=> 심민성  / 문의하기 , 문의하기 답변  textarea  수정 완료

src/main/resources/static/css/study/createStudy.css, src/main/resources/static/css/study/detailStudy.css, src/main/resources/static/css/study/feedStudy.css, src/main/resources/static/css/study/listStudy.css, src/main/resources/static/css/study/questionStudy.css, src/main/resources/static/css/study/workStudy.css, src/main/resources/static/js/study/workStudy.js, src/main/resources/templates/app/study/detailStudy.html, src/main/resources/templates/app/study/feedStudy.html, src/main/resources/templates/app/study/questionStudy.html, src/main/resources/templates/app/study/studyManagement.html, src/main/resources/templates/app/study/workStudy.html
[추성윤] 스터디 상세페이지 CSS 완료 / 상세_일감 페이지 탭 이동 JS 적용 / 상세페이지 스토리 탭 삭제
=> [추성윤] 스터디 상세페이지 CSS 완료 / 상세_일감 페이지 탭 이동 JS 적용 / 상세페이지 스토리 탭 삭제

src/main/resources/static/css/fix/chatting.css, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/fix/chattingBase.html, src/main/resources/templates/app/neosUser/userInfo2.html
채팅 모달 위치 조정 밑 첨부파일, 이모티콘 버튼 삭제, 색상 변경
=> 채팅 모달 위치 조정 밑 첨부파일, 이모티콘 버튼 삭제, 색상 변경

src/main/resources/static/css/fix/header.css, src/main/resources/static/css/fix/loginHeader.css, src/main/resources/templates/app/fix/footer.html, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/fix/loginHeader.html, src/main/resources/templates/app/main/loginMain.html, src/main/resources/templates/app/main/main.html
조성현 - 채팅창 버튼 위치 조정 / 헤더,푸터 반응형으로 수정 완료
=> 조성현 - 채팅창 버튼 위치 조정 / 헤더,푸터 반응형으로 수정 완료

src/main/resources/static/css/community/board.css
=> 박종우 커뮤니티 반응형 수정

src/main/resources/static/css/inquiry/inquiry.css, src/main/resources/static/css/inquiry/inquiryReply.css, src/main/resources/static/css/loginAndJoin/join.css, src/main/resources/static/css/loginAndJoin/login.css, src/main/resources/templates/app/inquiry/inquiry.html, src/main/resources/templates/app/inquiry/inquiryReply.html, src/main/resources/templates/app/loginAndJoin/join.html, src/main/resources/templates/app/loginAndJoin/login.html
심민성 문의하기 텍스트 수정 등록 / 로그인 회원가입 모달 완료
=> 심민성 문의하기 텍스트 수정 등록 / 로그인 회원가입 모달 완료

src/main/resources/static/css/fix/h_new.css, src/main/resources/static/css/fix/header.css, src/main/resources/templates/app/main/loginMain.html, src/main/resources/templates/app/main/main.html
=> 조성현 - 채팅창 아이콘 삭제

src/main/resources/static/css/inquiry/inquiry.css, src/main/resources/static/css/loginAndJoin/joinPage.css, src/main/resources/static/css/notice/noticeDetails.css, src/main/resources/templates/app/inquiry/inquiry.html, src/main/resources/templates/app/inquiry/inquiryReply.html, src/main/resources/templates/app/loginAndJoin/join.html, src/main/resources/templates/app/loginAndJoin/joinPage.html
심민성 문의하기 텍스트 등록 취소 댓글 열기 닫기 / 공지사항 상세보기 목록으로 중앙으로 완료
=> 심민성 문의하기 텍스트 등록 취소 댓글 열기 닫기 / 공지사항 상세보기 목록으로 중앙으로 완료

src/main/java/com/example/neosproject/controller/study/StudyController.java, src/main/resources/static/css/study/feedStudy.css, src/main/resources/static/css/study/questionStudy.css, src/main/resources/static/js/study/detailStudy.js, src/main/resources/static/js/study/feed-study.js, src/main/resources/static/js/study/listStudy.js, src/main/resources/static/js/study/questionStudy.js, src/main/resources/templates/app/study/feed-study.html, src/main/resources/templates/app/study/questionStudy.html
[추성윤] JS 80% 구현 完 : 본인 작성글, 댓글 수정 가능, 수정 중 취소 시 내용 그대로 유지 등
=> [추성윤] JS 80% 구현 完 : 본인 작성글, 댓글 수정 가능, 수정 중 취소 시 내용 그대로 유지 등

src/main/resources/static/css/myPage/myPage.css, src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/app/myPage/my.html
=> [김로사] 마이페이지 정보 v.1.2

src/main/resources/static/css/study/questionStudy.css, src/main/resources/static/js/study/feed-study.js, src/main/resources/static/js/study/questionStudy.js
[추성윤] JS 오류 수정 / 피드 작성 중 취소 관련
=> [추성윤] JS 오류 수정 / 피드 작성 중 취소 관련

src/main/resources/static/css/admin/userDetail.css, src/main/resources/static/css/community/board.css, src/main/resources/static/css/community/board4.css, src/main/resources/static/js/admin/inquiryList.js, src/main/resources/templates/app/admin/userDetail.html, src/main/resources/templates/app/community/counseling.html, src/main/resources/templates/app/community/freeboard.html
=> 박종우 퍼블리싱 최종.

src/main/resources/static/css/fix/chatting.css, src/main/resources/static/css/neosUser/neosListNext.css, src/main/resources/static/js/fix/chatting.js, src/main/resources/static/js/neosUser/neosListAfter.js, src/main/resources/static/js/neosUser/userInfo.js, src/main/resources/static/js/neosUser/userInfoNoLogin.js, src/main/resources/static/js/neosUser/userInfoNotInvite.js, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/neosUser/neosListAfter.html
<류호근> 채팅창 반응형 수정 완료 버그 및 오류 수정 완료, 퍼블리싱 최종
=> <류호근> 채팅창 반응형 수정 완료 버그 및 오류 수정 완료, 퍼블리싱 최종

src/main/resources/static/js/neosUser/neosListAfter.js, src/main/resources/templates/app/neosUser/neosListAfter.html
=> 류호근 네오스인 js 오류 수정

src/main/java/com/example/neosproject/controller/search/SearchController.java, src/main/resources/static/css/fix/header.css, src/main/resources/static/css/fix/loginHeader.css, src/main/resources/static/js/fix/login.js, src/main/resources/templates/app/main/main.html
조성현 - 반응형 페이지 최종 수정 / 주소명 변경 완료
=> 조성현 - 반응형 페이지 최종 수정 / 주소명 변경 완료

src/main/resources/static/css/neosUser/userInfo.css, src/main/resources/static/js/neosUser/userInfo.js, src/main/resources/templates/app/neosUser/myInfo.html, src/main/resources/templates/app/neosUser/neosListAfter.html, src/main/resources/templates/app/neosUser/neosListBefore.html, src/main/resources/templates/app/neosUser/userInfoNoLogin.html, src/main/resources/templates/app/neosUser/userInfoNotInvite.html, src/main/resources/templates/app/neosUser/userInfoYes.html
[유호근] 프로필 상세보기 스터디 부분 우리 프로젝트에 맞게 수정, 관련 js 수정
=> [유호근] 프로필 상세보기 스터디 부분 우리 프로젝트에 맞게 수정, 관련 js 수정

src/main/resources/static/css/myPage/myPage.css, src/main/resources/static/css/store/storeDetail.css, src/main/resources/templates/app/myPage/my.html, src/main/resources/templates/app/store/storeDetail.html
[김로사] 마이페이지 대학교 이메일 수정 / 자료상점 상세 댓글 작업중
=> [김로사] 마이페이지 대학교 이메일 수정 / 자료상점 상세 댓글 작업중

src/main/resources/static/css/myPage/myPage.css, src/main/resources/static/css/neosUser/modalList.css, src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/app/myPage/my.html, src/main/resources/templates/app/neosUser/modalList.html
=> 김로사 마이페이지 모달창 추가, css 수정

src/main/resources/static/css/study/detailStudy.css, src/main/resources/static/css/study/feedStudy.css, src/main/resources/static/css/study/questionStudy.css, src/main/resources/static/css/study/studyManagement.css, src/main/resources/static/css/study/studyModal.css, src/main/resources/static/css/study/workStudy.css
=> [추성윤] 스터디 관련 페이지 추가 수정

src/main/java/com/app/neosproject/entity/banner/Banner.java, src/main/java/com/app/neosproject/entity/chatting/Chatting.java, src/main/java/com/app/neosproject/entity/chatting/ChattingContent.java, src/main/java/com/app/neosproject/entity/college/College.java, src/main/java/com/app/neosproject/entity/community/Community.java, src/main/java/com/app/neosproject/entity/community/CommunityReReply.java, src/main/java/com/app/neosproject/entity/community/CommunityReply.java, src/main/java/com/app/neosproject/entity/counawling/Counawling.java, src/main/java/com/app/neosproject/entity/counawling/CounawlingReReply.java, src/main/java/com/app/neosproject/entity/counawling/CounawlingReply.java, src/main/java/com/app/neosproject/entity/follow/Follow.java, src/main/java/com/app/neosproject/entity/inquiry/Inquiry.java, src/main/java/com/app/neosproject/entity/neos/NeosPoint.java, src/main/java/com/app/neosproject/entity/neos/NeosPower.java, src/main/java/com/app/neosproject/entity/notice/Notice.java, src/main/java/com/app/neosproject/entity/store/Store.java, src/main/java/com/app/neosproject/entity/store/StoreFile.java, src/main/java/com/app/neosproject/entity/store/StoreReReply.java, src/main/java/com/app/neosproject/entity/store/StoreReply.java, src/main/java/com/app/neosproject/entity/study/Study.java, src/main/java/com/app/neosproject/entity/study/StudyFeed.java, src/main/java/com/app/neosproject/entity/study/StudyFeedReply.java, src/main/java/com/app/neosproject/entity/study/StudyFollow.java, src/main/java/com/app/neosproject/entity/study/StudyMember.java, src/main/java/com/app/neosproject/entity/study/StudyMilestone.java, src/main/java/com/app/neosproject/entity/study/StudyQuestion.java, src/main/java/com/app/neosproject/entity/study/StudyQuestionReply.java, src/main/java/com/app/neosproject/entity/study/StudySupporter.java, src/main/java/com/app/neosproject/entity/study/StudyWork.java, src/main/java/com/app/neosproject/entity/user/UserInterest.java
=> 심민성 엔티티 폴더 / 클래스 생성

src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/app/myPage/my.html, src/main/resources/templates/app/store/storeDetail.html
=> [김로사] - 마이페이지 mbti 기능 수정 완료

src/main/resources/static/js/neosUser/userInfo.js, src/main/resources/templates/app/neosUser/myInfo.html, src/main/resources/templates/app/neosUser/userInfoNoLogin.html, src/main/resources/templates/app/neosUser/userInfoNotInvite.html, src/main/resources/templates/app/neosUser/userInfoYes.html
류호근 프로필 상세보기 스터디 구독 버튼 부분 JS 오류 수정
=> 류호근 프로필 상세보기 스터디 구독 버튼 부분 JS 오류 수정

src/main/resources/static/css/myPage/myPage.css, src/main/resources/static/css/store/storeList.css, src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/app/myPage/my.html
조성현 - 마이페이지 버그 수정 / 네오력 소개 페이지 크기 수정 / 자료상점 글자색 수정 완료
=> 조성현 - 마이페이지 버그 수정 / 네오력 소개 페이지 크기 수정 / 자료상점 글자색 수정 완료

src/main/resources/static/css/store/storeDetail.css, src/main/resources/templates/app/store/storeDetail.html
=> [김로사] - 자료상점 상세 댓글(비밀댓글) 완료

src/main/resources/static/css/study/detailStudy.css, src/main/resources/static/css/study/listStudy.css, src/main/resources/static/css/study/studyModal.css, src/main/resources/static/js/study/createStudy.js, src/main/resources/static/js/study/detailStudy.js, src/main/resources/static/js/study/feed-study.js, src/main/resources/static/js/study/listStudy.js, src/main/resources/static/js/study/modalStudy.js, src/main/resources/templates/app/study/createStudy.html, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/feed-study.html, src/main/resources/templates/app/study/listStudy.html
[추성윤] 스터디 관련 모달 60% 완료 / 일부 CSS 수정
=> [추성윤] 스터디 관련 모달 60% 완료 / 일부 CSS 수정

src/main/resources/static/css/study/detailStudy.css, src/main/resources/static/css/study/feedStudy.css, src/main/resources/static/css/study/listStudy.css, src/main/resources/static/css/study/questionStudy.css, src/main/resources/static/css/study/studyManagement.css, src/main/resources/static/css/study/studyModal.css, src/main/resources/static/css/study/workStudy.css, src/main/resources/static/js/study/feed-study.js, src/main/resources/static/js/study/listStudy.js, src/main/resources/static/js/study/questionStudy.js, src/main/resources/static/js/study/studyManagement.js, src/main/resources/static/js/study/workStudy.js, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/feed-study.html, src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/app/study/questionStudy.html, src/main/resources/templates/app/study/studyManagement.html, src/main/resources/templates/app/study/workStudy.html
[추성윤] 스터디 생성, 목록, 상세보기 CSS, JS 완료(모달, 채팅 포함)
=> [추성윤] 스터디 생성, 목록, 상세보기 CSS, JS 완료(모달, 채팅 포함)

src/main/java/com/app/neos/repository/user/Search.java, src/main/java/com/app/neos/repository/user/UserCustomRepository.java, src/main/java/com/app/neos/repository/user/UserCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/user/UserRepository.java, src/main/resources/templates/app/admin/bannerEdit.html, src/main/resources/templates/app/fix/header.html, src/test/java/com/app/neos/entity/user/UserEntityTest.java, src/test/java/com/app/neos/entity/user/UserInterestEntityTest.java
=> 박종우 유저 테스트 및 헤더랑 배너 등록버튼 수정

src/main/java/com/app/neos/domain/chatting/ChattingDTO.java, src/main/java/com/app/neos/entity/chatting/Chatting.java, src/test/java/com/app/neos/entity/chatting/ChattingContentEntityTest.java, src/test/java/com/app/neos/entity/chatting/ChattingEntityTest.java
=> 조성현 - 채팅 단위 테스트 완료

src/main/java/com/app/neos/domain/store/StoreReReplyDTO.java, src/main/java/com/app/neos/entity/store/StoreReReply.java, src/main/resources/static/css/study/studyManagement.css, src/main/resources/static/js/fix/chatting.js, src/main/resources/static/js/study/workStudy.js, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/study/studyManagement.html, src/test/java/com/app/neos/entity/store/StoreEntityTest.java, src/test/java/com/app/neos/entity/store/StoreFileEntityTest.java, src/test/java/com/app/neos/entity/store/StoreReReplyEntityTest.java, src/test/java/com/app/neos/entity/store/StoreReplyEntityTest.java
[추성윤] 자료상점 단위테스트 / 스터디, 채팅 JS 충돌, 오류 수정 중
=> [추성윤] 자료상점 단위테스트 / 스터디, 채팅 JS 충돌, 오류 수정 중

src/main/java/com/app/neos/entity/study/Study.java, src/main/java/com/app/neos/entity/study/StudySupporter.java, src/main/java/com/app/neos/entity/study/StudyWork.java, src/main/java/com/app/neos/repository/study/StudyWorkRepository.java, src/test/java/com/app/neos/entity/banner/BannerEntityTest.java, src/test/java/com/app/neos/entity/notice/NoticeEntityTest.java, src/test/java/com/app/neos/entity/study/StudyEntityTest.java, src/test/java/com/app/neos/entity/study/StudyFeedEntityTest.java, src/test/java/com/app/neos/entity/study/StudyFeedReplyEntityTest.java, src/test/java/com/app/neos/entity/study/StudyFollowEntityTest.java, src/test/java/com/app/neos/entity/study/StudyMemberEntityTest.java, src/test/java/com/app/neos/entity/study/StudyMileStoneEntityTest.java, src/test/java/com/app/neos/entity/study/StudyQuestionEntityTest.java, src/test/java/com/app/neos/entity/study/StudyQuestionReplyEntityTest.java, src/test/java/com/app/neos/entity/study/StudySupporterEntityTest.java, src/test/java/com/app/neos/entity/study/StudyWorkEntityTest.java
류호근 Repository 오타 수정 및 관리자, 공지사항, 스터디 crud 테스트 완료
=> 류호근 Repository 오타 수정 및 관리자, 공지사항, 스터디 crud 테스트 완료

src/main/java/com/app/neos/controller/community/MoveController.java, src/main/java/com/app/neos/domain/community/CommunityDTO.java, src/main/java/com/app/neos/domain/community/CommunityReplyDTO.java, src/main/java/com/app/neos/domain/counseling/CounselingDTO.java, src/main/java/com/app/neos/entity/community/Community.java, src/main/java/com/app/neos/entity/community/CommunityReReply.java, src/main/java/com/app/neos/entity/community/CommunityReply.java, src/main/java/com/app/neos/entity/counseling/Counseling.java, src/test/java/com/app/neos/entity/community/CommunityEntityTest.java, src/test/java/com/app/neos/entity/community/CommunityReReplyEntityTest.java, src/test/java/com/app/neos/entity/community/CommunityReplyEntityTest.java, src/test/java/com/app/neos/entity/counseling/CounselingEntityTest.java, src/test/java/com/app/neos/entity/counseling/CounselingReReplyEntityTest.java, src/test/java/com/app/neos/entity/counseling/CounselingReplyEntityTest.java
[김로사] - 커뮤니티(자유, 고민 게시판) 단위 테스트 완료
=> [김로사] - 커뮤니티(자유, 고민 게시판) 단위 테스트 완료

src/main/resources/static/js/fix/chatting.js, src/main/resources/static/js/study/detailStudy.js, src/main/resources/static/js/study/feed-study.js, src/main/resources/static/js/study/modalStudy.js, src/main/resources/static/js/study/questionStudy.js, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/feed-study.html, src/main/resources/templates/app/study/questionStudy.html, src/main/resources/templates/app/study/studyManagement.html
=> [추성윤] 스터디, 채팅 공통부분 JS 통합 完

src/main/resources/templates/app/main/main.html, src/test/java/com/app/neos/entity/chatting/ChattingEntityTest.java
=> 조성현 - 메인페이지 수정 완료

src/main/resources/templates/app/main/main.html
=> [추성윤] 메인 스터디 목록 구독 기능 추가

src/main/resources/static/css/study/feedStudy.css, src/main/resources/static/css/study/questionStudy.css, src/main/resources/static/js/fix/chatting.js, src/main/resources/static/js/study/createStudy.js, src/main/resources/templates/app/neosUser/modalList.html, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/feed-study.html, src/main/resources/templates/app/study/questionStudy.html, src/main/resources/templates/app/study/studyManagement.html, src/main/resources/templates/app/study/workStudy.html
=> [추성윤] 버그 테스트 수정 完

src/main/resources/static/css/study/detailStudy.css, src/main/resources/static/css/study/studyManagement.css, src/main/resources/templates/app/myPage/my.html, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/studyManagement.html
=> [추성윤] 마이페이지 구독하기 버튼 구현

build.gradle, src/main/java/com/app/neos/controller/join/JoinController.java, src/main/java/com/app/neos/controller/login/LoginController.java, src/main/java/com/app/neos/domain/user/UserDTO.java, src/main/java/com/app/neos/entity/user/User.java, src/main/java/com/app/neos/repository/user/UserCustomRepository.java, src/main/java/com/app/neos/repository/user/UserCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/user/UserInterestRepository.java, src/main/java/com/app/neos/repository/user/UserRepository.java, src/main/java/com/app/neos/service/join/JoinService.java, src/main/java/com/app/neos/service/join/KaKaoLoginService.java, src/main/java/com/app/neos/service/join/KaKaoService.java, src/main/java/com/app/neos/service/login/LoginService.java, src/main/resources/static/js/fix/header.js, src/main/resources/static/js/loginAndJoin/joinOk.js, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/loginAndJoin/joinPage.html, src/main/resources/templates/app/main/main.html, src/test/java/com/app/neos/entity/banner/BannerEntityTest.java, src/test/java/com/app/neos/entity/user/UserEntityTest.java
카카오톡 대학 정보 없을 때 회원가입 가능
로그인 카카오톡 가능
=> 박종우 회원가입 로그인 ver1.0

src/main/resources/templates/app/main/main.html
=> 조성현 - 메인 페이지 수정

src/main/java/com/app/neos/controller/login/LoginController.java, src/main/java/com/app/neos/controller/login/LoginRestController.java, src/main/java/com/app/neos/controller/login/LogoutController.java, src/main/java/com/app/neos/domain/user/UserDTO.java, src/main/java/com/app/neos/entity/user/User.java, src/main/java/com/app/neos/repository/user/UserCustomRepository.java, src/main/java/com/app/neos/repository/user/UserCustomRepositoryImpl.java, src/main/java/com/app/neos/service/login/LoginService.java, src/main/resources/static/js/fix/header.js, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/main/TestMain.html, src/main/resources/templates/app/main/main.html, src/test/java/com/app/neos/entity/user/UserEntityTest.java
카카오톡 로그인 구현
회원가입 구현 30% (대학정보 없을 시 회원 가입 가능)
로그아웃 구현
로그인 시 네오스 경험치 10 추가, 일정 조건마다 레벨업 80%(구간은 임의 설정)
=> 박종우 로그인 /회원가입 ver1.1

src/main/java/com/app/neos/controller/admin/AdminTestController.java, src/main/java/com/app/neos/domain/college/CollegeDTO.java, src/main/java/com/app/neos/entity/college/College.java, src/main/java/com/app/neos/repository/college/CollegeCustomRepository.java, src/main/java/com/app/neos/repository/college/CollegeCustomRepositoryImpl.java, src/main/java/com/app/neos/service/admin/AdminService.java, src/main/resources/templates/app/admin/universeDetail.html, src/main/resources/templates/app/admin/universeList.html, src/main/resources/templates/app/admin/universeWrite.html, src/test/java/com/app/neos/entity/college/CollegeEntityTest.java, src/test/java/com/app/neos/service/admin/AdminServiceTest.java
=> [유호근] 관리자페이지 대학 상세보기 완료

build.gradle, src/main/java/com/app/neos/config/EmailConfig.java, src/main/java/com/app/neos/controller/join/EmailController.java, src/main/java/com/app/neos/controller/join/JoinController.java, src/main/java/com/app/neos/controller/login/LoginController.java, src/main/java/com/app/neos/entity/user/User.java, src/main/java/com/app/neos/service/join/EmailService.java, src/main/java/com/app/neos/service/join/EmailServiceImpl.java, src/main/java/com/app/neos/service/join/JoinService.java, src/main/resources/email.properties, src/main/resources/templates/app/loginAndJoin/joinPage.html, src/main/resources/templates/app/main/TestMain.html, src/main/resources/templates/app/main/main.html
이메일 인증 가능
로그인 처리
카카오톡 구현 90% 완료
=> 박종우 회원가입 대학교 선택가능

src/main/java/com/app/neos/controller/store/StoreController.java, src/main/java/com/app/neos/service/myPage/MyPageService.java, src/main/java/com/app/neos/service/store/StoreService.java, src/main/resources/static/js/store/storeCreate.js, src/main/resources/static/js/study/listStudy.js, src/main/resources/static/js/study/workStudy.js, src/main/resources/templates/app/store/storeCreate.html, src/main/resources/templates/app/study/createStudy.html, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/feed-study.html, src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/app/study/questionStudy.html, src/main/resources/templates/app/study/studyManagement.html, src/main/resources/templates/app/study/workStudy.html, src/test/java/com/app/neos/service/myPage/MyPageServiceTest.java, src/test/java/com/app/neos/service/store/StoreServiceTest.java
[추성윤] 스터디 관련 헤더 전부 적용 / 자료상점 글쓰기 (첨부파일 제외) 완료
=> [추성윤] 스터디 관련 헤더 전부 적용 / 자료상점 글쓰기 (첨부파일 제외) 완료

src/main/java/com/app/neos/controller/join/JoinController.java, src/main/java/com/app/neos/controller/login/LoginController.java, src/main/java/com/app/neos/controller/login/LogoutController.java, src/main/java/com/app/neos/controller/study/StudyController.java, src/main/java/com/app/neos/domain/study/StudyDTO.java, src/main/java/com/app/neos/service/join/GoogleService.java, src/main/java/com/app/neos/service/join/NaverService.java, src/main/resources/static/js/fix/header.js, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/main/main.html
=> 박종우 로그인 회원가입 카카오 네이버 완료,

src/main/java/com/app/neos/controller/login/LoginController.java, src/main/java/com/app/neos/entity/user/User.java, src/main/java/com/app/neos/service/login/LoginService.java, src/main/resources/templates/app/study/createStudy.html, src/test/java/com/app/neos/service/join/JoinServiceTest.java
로그인 시 정보 없을 때 제대로 안가져와지는점, 세션에 담기는 값 수정
=> 박종우 로그인 방식 변경

src/test/java/com/app/neos/entity/store/StoreEntityTest.java, src/test/java/com/app/neos/service/store/StoreServiceTest.java
=> [추성윤] 테스트 오류 수정

src/main/java/com/app/neos/controller/community/CommunityController.java, src/main/java/com/app/neos/controller/community/CommunityRestController.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepository.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/counseling/CounselingCustomRepository.java, src/main/java/com/app/neos/repository/counseling/CounselingCustomRepositoryImpl.java, src/main/java/com/app/neos/service/community/CommunityService.java, src/main/java/com/app/neos/service/counseling/CounselingService.java, src/main/resources/static/css/community/board3.css, src/main/resources/static/js/community/freeBoardAjax.js, src/main/resources/static/js/community/freeboard.js, src/main/resources/templates/app/community/counselingboard.html, src/main/resources/templates/app/community/freeboard.html, src/test/java/com/app/neos/service/community/CommunityServiceTest.java
=> [김로사] - 커뮤니티 ajax로 변경중

src/main/java/com/app/neos/controller/login/LoginRestController.java, src/main/java/com/app/neos/controller/study/StudyController.java, src/main/java/com/app/neos/domain/study/StudyDTO.java, src/main/java/com/app/neos/domain/study/StudySearch.java, src/main/java/com/app/neos/domain/user/UserDTO.java, src/main/java/com/app/neos/entity/study/Study.java, src/main/java/com/app/neos/repository/study/StudyCustomRepository.java, src/main/java/com/app/neos/repository/study/StudyCustomRepositoryImpl.java, src/main/java/com/app/neos/service/study/StudyService.java, src/main/java/com/app/neos/type/study/StudyRecruitStatus.java, src/main/resources/static/js/study/createStudy.js, src/main/resources/templates/app/loginAndJoin/joinPage.html, src/main/resources/templates/app/study/createStudy.html, src/main/resources/templates/app/study/listStudy.html, src/test/java/com/app/neos/entity/college/CollegeEntityTest.java, src/test/java/com/app/neos/entity/study/StudyEntityTest.java, src/test/java/com/app/neos/service/join/JoinServiceTest.java, src/test/java/com/app/neos/service/study/StudyServiceTest.java
=> 박종우 스터디 글 등록 가능 페이징 처리 70퍼센트 완료

src/main/java/com/app/neos/config/WebMvcConfig.java, src/main/java/com/app/neos/controller/admin/AdminRestController.java, src/main/java/com/app/neos/controller/admin/AdminTestController.java, src/main/java/com/app/neos/domain/banner/BannerDTO.java, src/main/java/com/app/neos/entity/banner/Banner.java, src/main/java/com/app/neos/repository/banner/BannerCustomRepository.java, src/main/java/com/app/neos/repository/banner/BannerCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/college/CollegeCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/notice/NoticeCustomRepository.java, src/main/java/com/app/neos/repository/notice/NoticeCustomRepositoryImpl.java, src/main/java/com/app/neos/service/admin/AdminService.java, src/main/java/com/app/neos/type/banner/BannerStatus.java, src/main/resources/application.yml, src/main/resources/static/css/admin/bannerEdit.css, src/main/resources/templates/app/admin/adminPaging.html, src/main/resources/templates/app/admin/bannerEdit.html, src/main/resources/templates/app/admin/configBanner.html, src/main/resources/templates/app/admin/noticePost.html, src/main/resources/templates/app/admin/universeList.html, src/main/resources/templates/app/admin/universeWrite.html, src/test/java/com/app/neos/entity/banner/BannerEntityTest.java, src/test/java/com/app/neos/entity/college/CollegeEntityTest.java
[유호근] 배너, 대학 이미지 등록, 목록에서 이미지 뿌리기 완료 페이징 처리 진행중 공지사항 등록 완료
=> [유호근] 배너, 대학 이미지 등록, 목록에서 이미지 뿌리기 완료 페이징 처리 진행중 공지사항 등록 완료

src/main/java/com/app/neos/controller/login/LoginRestController.java, src/main/java/com/app/neos/controller/login/LogoutController.java, src/main/java/com/app/neos/controller/study/StudyController.java, src/main/java/com/app/neos/controller/study/StudyRestController.java, src/main/java/com/app/neos/entity/study/Study.java, src/main/java/com/app/neos/repository/study/StudyCustomRepository.java, src/main/java/com/app/neos/repository/study/StudyCustomRepositoryImpl.java, src/main/java/com/app/neos/service/join/NaverService.java, src/main/java/com/app/neos/service/study/StudyService.java, src/main/resources/static/css/study/listStudy.css, src/main/resources/static/js/study/listStudy.js, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/listStudy.html, src/test/java/com/app/neos/service/study/StudyServiceTest.java
=> 박종우 스터디 글쓰기 완료, 리스트 페이징 처리 및 동적쿼리 rest방식으로 구현 완료

src/main/java/com/app/neos/controller/community/CommunityController.java, src/main/java/com/app/neos/controller/community/CommunityRestController.java, src/main/java/com/app/neos/domain/community/CommunityDTO.java, src/main/java/com/app/neos/entity/community/Community.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepository.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepositoryImpl.java, src/main/java/com/app/neos/service/community/CommunityService.java, src/main/java/com/app/neos/service/join/JoinService.java, src/main/resources/static/css/community/board2.css, src/main/resources/static/js/community/freeBoardAjax.js, src/main/resources/static/js/community/freeboard.js, src/main/resources/templates/app/community/counselingboard.html, src/main/resources/templates/app/community/freeboard.html, src/test/java/com/app/neos/service/community/CommunityServiceTest.java
[김로사] - 커뮤니티 글작성, 목록 (페이징 준비중), 수정 작업중
=> [김로사] - 커뮤니티 글작성, 목록 (페이징 준비중), 수정 작업중

src/main/java/com/app/neos/controller/community/CommunityRestController.java, src/main/java/com/app/neos/entity/community/Community.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepository.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepositoryImpl.java, src/main/java/com/app/neos/service/community/CommunityService.java, src/main/resources/static/css/community/board3.css, src/main/resources/static/css/community/board4.css, src/main/resources/static/js/community/freeBoardAjax.js, src/main/resources/static/js/community/freeboard.js, src/main/resources/templates/app/community/freeboard.html, src/test/java/com/app/neos/service/community/CommunityServiceTest.java
[김로사] - 커뮤니티(자유) 작성&수정&삭제 완료, 목록 페이징 처리 작업중
=> [김로사] - 커뮤니티(자유) 작성&수정&삭제 완료, 목록 페이징 처리 작업중

src/main/java/com/app/neos/controller/community/CommunityRestController.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepository.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepositoryImpl.java, src/main/resources/static/js/community/freeBoardAjax.js, src/main/resources/templates/app/community/freeboard.html
[김로사] - 커뮤니티(자유) 목록 더보기 페이징 완료, 수정 완료, 삭제 버그 수정중
=> [김로사] - 커뮤니티(자유) 목록 더보기 페이징 완료, 수정 완료, 삭제 버그 수정중

src/main/java/com/app/neos/controller/study/StudyController.java, src/main/java/com/app/neos/controller/study/StudyQuestionReplyRestController.java, src/main/java/com/app/neos/controller/study/StudyQuestionRestController.java, src/main/java/com/app/neos/controller/study/StudyRestController.java, src/main/java/com/app/neos/domain/study/StudyDTO.java, src/main/java/com/app/neos/domain/study/StudyQuestionDTO.java, src/main/java/com/app/neos/domain/study/StudyQuestionReplyDTO.java, src/main/java/com/app/neos/entity/study/Study.java, src/main/java/com/app/neos/entity/study/StudyQuestion.java, src/main/java/com/app/neos/entity/study/StudyQuestionReply.java, src/main/java/com/app/neos/repository/study/StudyCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/study/StudyQuestionCustomRepository.java, src/main/java/com/app/neos/repository/study/StudyQuestionCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/study/StudyQuestionReplyCustomRepository.java, src/main/java/com/app/neos/repository/study/StudyQuestionReplyCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/study/StudyQuestionRepository.java, src/main/java/com/app/neos/service/study/StudyQuestionReplyService.java, src/main/java/com/app/neos/service/study/StudyQuestionService.java, src/main/java/com/app/neos/service/study/StudyService.java, src/main/resources/static/css/study/detailStudy.css, src/main/resources/static/js/fix/header.js, src/main/resources/static/js/study/listStudy.js, src/main/resources/static/js/study/questionStudy.js, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/app/study/questionStudy.html, src/test/java/com/app/neos/entity/study/StudyQuestionEntityTest.java, src/test/java/com/app/neos/entity/study/StudyQuestionReplyEntityTest.java, src/test/java/com/app/neos/service/study/StudyQuestionService.java
=> 박종우 스터디 질문 80% 완료

src/main/java/com/app/neos/controller/login/LogoutController.java, src/main/java/com/app/neos/service/join/KaKaoLoginService.java, src/main/resources/application.yml, src/main/resources/static/js/fix/header.js, src/main/resources/templates/app/fix/header.html
=> 카카오 로그아웃 수정

src/main/java/com/app/neos/controller/admin/AdminTestController.java, src/main/java/com/app/neos/controller/notice/NoticeController.java, src/main/java/com/app/neos/domain/study/StudyDTO.java, src/main/java/com/app/neos/domain/user/UserDTO.java, src/main/java/com/app/neos/entity/community/Community.java, src/main/java/com/app/neos/repository/admin/AdminCustomRepository.java, src/main/java/com/app/neos/repository/admin/AdminCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/admin/AdminUserRepository.java, src/main/java/com/app/neos/service/admin/AdminCustomService.java, src/main/java/com/app/neos/service/admin/AdminService.java, src/main/resources/application.yml, src/main/resources/templates/app/admin/adminNavBar.html, src/main/resources/templates/app/admin/adminPaging.html, src/main/resources/templates/app/admin/studyManagement.html, src/main/resources/templates/app/admin/universeWrite.html, src/main/resources/templates/app/admin/userList.html, src/test/java/com/app/neos/entity/community/CommunityEntityTest.java, src/test/java/com/app/neos/service/admin/AdminServiceTest.java
=> [ 유호근 ] 시연 전 푸쉬

src/main/java/com/app/neos/controller/store/StoreController.java, src/main/java/com/app/neos/service/store/StoreService.java, src/main/resources/templates/app/store/storeDetail.html, src/main/resources/templates/app/store/storeUpdate.html
[추성윤] 자료상점 게시글 수정 80퍼, 삭제 100퍼 완료
=> [추성윤] 자료상점 게시글 수정 80퍼, 삭제 100퍼 완료

src/main/java/com/app/neos/controller/study/StudyController.java, src/main/java/com/app/neos/controller/study/StudyMemberController.java, src/main/java/com/app/neos/domain/study/StudyDTO.java, src/main/java/com/app/neos/domain/study/StudyMemberDTO.java, src/main/java/com/app/neos/domain/study/StudySupporterDTO.java, src/main/java/com/app/neos/entity/study/Study.java, src/main/java/com/app/neos/entity/study/StudyFeed.java, src/main/java/com/app/neos/entity/study/StudyFeedReply.java, src/main/java/com/app/neos/entity/study/StudyFollow.java, src/main/java/com/app/neos/entity/study/StudyMember.java, src/main/java/com/app/neos/entity/study/StudyMilestone.java, src/main/java/com/app/neos/entity/study/StudyQuestion.java, src/main/java/com/app/neos/entity/study/StudyQuestionReply.java, src/main/java/com/app/neos/entity/study/StudySupporter.java, src/main/java/com/app/neos/entity/study/StudyWork.java, src/main/java/com/app/neos/service/study/StudyMemberService.java, src/main/java/com/app/neos/service/study/StudyService.java, src/main/java/com/app/neos/type/study/supporter/StudySupporterStatus.java, src/main/resources/application.yml, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/app/study/questionStudy.html, src/main/resources/templates/app/study/studyManagement.html, src/test/java/com/app/neos/entity/study/StudyMemberEntityTest.java, src/test/java/com/app/neos/entity/study/StudySupporterEntityTest.java, src/test/java/com/app/neos/service/study/StudyFollowTest.java
박종우 스터디 게시글 관리중 정보수정 완료, 지원하기 버튼 활성화 지원시 관리자는 지원현황 볼수 있음
=> 박종우 스터디 게시글 관리중 정보수정 완료, 지원하기 버튼 활성화 지원시 관리자는 지원현황 볼수 있음

src/main/java/com/app/neos/controller/admin/AdminTestController.java, src/main/java/com/app/neos/domain/community/CommunityDTO.java, src/main/java/com/app/neos/domain/community/CommunityReplyDTO.java, src/main/java/com/app/neos/domain/counseling/CounselingDTO.java, src/main/java/com/app/neos/domain/counseling/CounselingReplyDTO.java, src/main/java/com/app/neos/domain/store/StoreDTO.java, src/main/java/com/app/neos/domain/store/StoreReplyDTO.java, src/main/java/com/app/neos/domain/study/StudyFeedReplyDTO.java, src/main/java/com/app/neos/repository/admin/AdminCustomRepository.java, src/main/java/com/app/neos/repository/admin/AdminCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/admin/AdminStudyFollowRepository.java, src/main/java/com/app/neos/service/admin/AdminService.java, src/main/resources/templates/app/admin/adminNavBar.html, src/main/resources/templates/app/admin/counComment.html, src/main/resources/templates/app/admin/counselingBoardManagement.html, src/main/resources/templates/app/admin/freeBoardComment.html, src/main/resources/templates/app/admin/freeBoardManagement.html, src/main/resources/templates/app/admin/freeShopBoardManagement.html, src/main/resources/templates/app/admin/shopComment.html, src/main/resources/templates/app/admin/studyComment.html, src/main/resources/templates/app/admin/studyManagement.html, src/main/resources/templates/app/admin/universeList.html, src/main/resources/templates/app/admin/userList.html, src/test/java/com/app/neos/entity/counseling/CounselingEntityTest.java, src/test/java/com/app/neos/service/admin/AdminServiceTest.java
[유호근] 게시판 관리, 댓글 관리 검색 제외 모두 구현
=> [유호근] 게시판 관리, 댓글 관리 검색 제외 모두 구현

src/main/java/com/app/neos/controller/inquiry/InquiryController.java, src/test/java/com/app/neos/service/inquiry/InquiryServiceTest.java
심민성     inquiryServiceTest 주석 완료
=> 심민성     inquiryServiceTest 주석 완료

src/main/java/com/app/neos/controller/inquiry/InquiryController.java, src/main/java/com/app/neos/controller/neosUser/NeosUserController.java, src/main/java/com/app/neos/controller/neosUser/NeosUserRestController.java, src/main/java/com/app/neos/domain/inquiry/InquiryDTO.java, src/main/java/com/app/neos/repository/inquiry/InquiryCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/neos/MainBannerCustomRepository.java, src/main/java/com/app/neos/repository/neos/MainBannerCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/neos/NeosUserCustomRepository.java, src/main/java/com/app/neos/repository/neos/NeosUserCustomRepositoryImpl.java, src/main/java/com/app/neos/service/main/MainService.java, src/main/java/com/app/neos/service/neosUser/NeosUserService.java, src/main/resources/static/js/neosUser/neosListAfter.js, src/main/resources/templates/app/inquiry/inquiryReply.html, src/main/resources/templates/app/main/main.html, src/main/resources/templates/app/neosUser/neosListAfter.html, src/test/java/com/app/neos/service/neosUser/NeosUserServiceTest.java
심민성  메인 화면 뿌리기  / 문의하기 질문 답변 완료 / 네오스인 검색 조회 진행중
=> 심민성  메인 화면 뿌리기  / 문의하기 질문 답변 완료 / 네오스인 검색 조회 진행중

src/main/java/com/app/neos/controller/neosUser/NeosUserRestController.java, src/main/java/com/app/neos/domain/user/FollowDTO.java, src/main/java/com/app/neos/entity/follow/Follow.java, src/main/java/com/app/neos/entity/user/User.java, src/main/java/com/app/neos/service/neosUser/NeosUserService.java, src/main/java/com/app/neos/type/point/NeosPowerContent.java, src/main/resources/static/css/neosUser/neosListNext.css, src/main/resources/static/js/neosUser/neosListAfter.js, src/main/resources/templates/app/main/main.html, src/main/resources/templates/app/neosUser/neosListAfter.html, src/main/resources/templates/app/neosUser/userInfoYes.html, src/test/java/com/app/neos/entity/banner/BannerEntityTest.java
심민성 모집하기 검색 완료 / 네오력 적립차감 완료 / 팔로우 진행중
=> 심민성 모집하기 검색 완료 / 네오력 적립차감 완료 / 팔로우 진행중

src/main/java/com/app/neos/domain/user/UserDTO.java
=> 심민성 UserDTO 컬럼 추가

src/main/java/com/app/neos/domain/Alarm/AlarmDTO.java, src/main/java/com/app/neos/entity/alarm/Alarm.java, src/main/java/com/app/neos/service/alarm/AlarmService.java
=> 알람 서비스단 완료

src/main/java/com/app/neos/config/WebMvcConfig.java, src/main/java/com/app/neos/controller/admin/AdminRestController.java, src/main/java/com/app/neos/controller/alarm/AlarmRestController.java, src/main/java/com/app/neos/controller/study/StudyController.java, src/main/java/com/app/neos/entity/inquiry/Inquiry.java, src/main/java/com/app/neos/interceptor/AlarmInterceptor.java, src/main/java/com/app/neos/repository/alarm/AlarmCustomRepository.java, src/main/java/com/app/neos/repository/alarm/AlarmCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/study/StudySupporterCustomRepository.java, src/main/java/com/app/neos/repository/study/StudySupporterCustomRepositoryImpl.java, src/main/java/com/app/neos/service/alarm/AlarmService.java, src/main/java/com/app/neos/service/study/StudyMemberService.java, src/main/java/com/app/neos/service/study/StudyQuestionReplyService.java, src/main/resources/static/js/fix/header.js, src/main/resources/templates/app/fix/header.html, src/test/java/com/app/neos/service/study/UserSearchTest.java
박종우 스터디 오류 해결 및 알림 서비스 인터셉터 구현
=> 박종우 스터디 오류 해결 및 알림 서비스 인터셉터 구현

src/main/java/com/app/neos/controller/neosUser/NeosUserController.java, src/main/java/com/app/neos/repository/follow/FollowCustomRepository.java, src/main/java/com/app/neos/repository/follow/FollowCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/neos/NeosUserCustomRepositoryImpl.java, src/main/java/com/app/neos/service/neosUser/NeosUserService.java, src/main/resources/templates/app/neosUser/neosListAfter.html
=> 심민성 팔로우 서비스 테스트 까지 완료

src/main/java/com/app/neos/controller/alarm/AlarmRestController.java, src/main/java/com/app/neos/repository/study/StudyCustomRepository.java, src/main/java/com/app/neos/repository/study/StudyCustomRepositoryImpl.java, src/main/java/com/app/neos/service/study/StudyService.java, src/main/resources/static/css/fix/header.css, src/main/resources/static/js/fix/header.js, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/app/study/workStudy.html, src/test/java/com/app/neos/service/study/UserSearchTest.java
=> 박종우 헤더 호버메뉴 수정

src/main/java/com/app/neos/controller/search/SearchController.java, src/main/java/com/app/neos/controller/search/SearchRestController.java, src/main/java/com/app/neos/entity/community/CommunityLike.java, src/main/java/com/app/neos/entity/community/CommunityReply.java, src/main/java/com/app/neos/entity/counseling/Counseling.java, src/main/java/com/app/neos/entity/counseling/CounselingReply.java, src/main/java/com/app/neos/entity/neos/NeosPoint.java, src/main/java/com/app/neos/entity/store/Store.java, src/main/java/com/app/neos/entity/store/StoreFile.java, src/main/java/com/app/neos/repository/search/SearchCustomRepository.java, src/main/java/com/app/neos/repository/search/SearchCustomRepositoryImpl.java, src/main/java/com/app/neos/service/community/CommunityReplyService.java, src/main/java/com/app/neos/service/myPage/PayService.java, src/main/java/com/app/neos/service/search/SearchService.java, src/main/resources/static/css/community/board2.css, src/main/resources/static/css/search/searchComplete.css, src/main/resources/static/js/community/freeBoardReplyAjax.js, src/main/resources/static/js/search/searchAjax.js, src/main/resources/templates/app/community/freeboard.html, src/main/resources/templates/app/fix/chargeInput.html, src/main/resources/templates/app/search/searchAfter.html, src/main/resources/templates/app/search/searchBefore.html, src/main/resources/templates/app/search/searchComplete.html
[김로사] - 결제 후 네오력 적립 수정, 검색 완료(페이징 처리중)
=> [김로사] - 결제 후 네오력 적립 수정, 검색 완료(페이징 처리중)

src/main/java/com/app/neos/interceptor/AlarmInterceptor.java, src/main/resources/templates/app/fix/header.html
인터셉터 시점 변경. posthandle->prehandle
=> 인터셉터 시점 변경. posthandle->prehandle

src/main/java/com/app/neos/controller/myPage/MyPageRestController.java, src/main/java/com/app/neos/domain/store/StoreDTO.java, src/main/java/com/app/neos/repository/store/StoreCustomRepositoryImpl.java, src/main/java/com/app/neos/service/myPage/MyPageService.java, src/main/resources/static/css/myPage/myPage.css, src/main/resources/static/css/store/storeList.css, src/main/resources/static/js/myPage/myPage.js, src/main/resources/static/js/myPage/myPageAjax.js, src/main/resources/static/js/myPage/myPageDom.js, src/main/resources/static/js/store/storeDetail.js, src/main/resources/static/js/store/storeList.js, src/main/resources/templates/app/myPage/my.html, src/main/resources/templates/app/store/storeDetail-free.html, src/main/resources/templates/app/store/storeDetail-pay.html, src/main/resources/templates/app/store/storeDetail-purchase.html, src/main/resources/templates/app/store/storeDetail.html, src/main/resources/templates/app/store/storeList.html
=> [추성윤] 편의성 개선

src/main/java/com/app/neos/controller/chatting/ChatRestController.java, src/main/java/com/app/neos/controller/handler/WebSocketHandler.java, src/main/java/com/app/neos/domain/chatting/ChattingRoomDTO.java, src/main/java/com/app/neos/entity/chatting/ChattingRoom.java, src/main/java/com/app/neos/repository/chatting/ChatContentCustomRepositoryImpl.java, src/main/java/com/app/neos/service/fix/FixService.java, src/main/resources/static/css/fix/chatting.css, src/main/resources/static/js/community/freeBoardAjax.js, src/main/resources/static/js/fix/chattingAll.js, src/main/resources/static/js/main/maindummy.js, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/main/main.html, src/test/java/com/app/neos/service/fix/FixServiceTest.java
=> 조성현 - 실시간 채팅 완료

src/main/java/com/app/neos/controller/main/MainController.java, src/main/java/com/app/neos/controller/neosUser/NeosUserController.java, src/main/java/com/app/neos/controller/neosUser/NeosUserRestController.java, src/main/java/com/app/neos/domain/store/StoreDTO.java, src/main/java/com/app/neos/repository/neos/MainStoreCustomRepository.java, src/main/java/com/app/neos/repository/neos/MainStoreCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/neos/MainUserCustomRepository.java, src/main/java/com/app/neos/repository/neos/MainUserCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/neos/NeosStudyCustomRepository.java, src/main/java/com/app/neos/repository/neos/NeosStudyCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/neos/NeosUserCustomRepository.java, src/main/java/com/app/neos/repository/neos/NeosUserCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/user/UserCustomRepository.java, src/main/java/com/app/neos/service/main/MainService.java, src/main/java/com/app/neos/service/neosUser/NeosUserService.java, src/main/resources/static/css/inquiry/inquiryReply.css, src/main/resources/static/css/notice/noticeDetails.css, src/main/resources/static/js/neosUser/neosListAfter.js, src/main/resources/templates/app/inquiry/inquiryReply.html, src/main/resources/templates/app/main/main.html, src/main/resources/templates/app/neosUser/neosListAfter.html, src/main/resources/templates/app/neosUser/userInfoYes.html, src/test/java/com/app/neos/entity/store/StoreEntityTest.java, src/test/java/com/app/neos/entity/study/StudyEntityTest.java, src/test/java/com/app/neos/entity/user/UserEntityTest.java
=> 심민성 문의하기 상세보기 메인 완료

src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/app/study/studyManagement.html, src/test/java/com/app/neos/entity/chatting/ChattingRoomEntityTest.java, src/test/java/com/app/neos/service/login/LoginServiceTest.java
=> [유호근] 더미데이터 테스트에 추가

src/main/java/com/app/neos/controller/join/JoinController.java, src/main/java/com/app/neos/controller/login/LoginController.java, src/main/java/com/app/neos/controller/login/LogoutController.java, src/main/java/com/app/neos/controller/main/MainController.java, src/main/java/com/app/neos/entity/user/User.java, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/main/certificationNeed.html, src/main/resources/templates/app/main/main.html, src/main/resources/templates/app/study/createStudy.html, src/main/resources/templates/app/study/detail-study.html, src/main/resources/templates/app/study/listStudy.html, src/main/resources/templates/error/500.html
로그인 로그아웃 알럿 삭제, 메인페이지 컨트롤러 경로 변경, 로그인 인증페이지 연결, 레벨업 구간 수정
=> 로그인 로그아웃 알럿 삭제, 메인페이지 컨트롤러 경로 변경, 로그인 인증페이지 연결, 레벨업 구간 수정

src/main/java/com/app/neos/controller/myPage/MyPageRestController.java, src/main/resources/static/js/myPage/myPageAjax.js, src/main/resources/templates/app/myPage/my.html, src/main/resources/templates/app/store/storeDetail-free.html, src/main/resources/templates/app/store/storeDetail-pay.html, src/main/resources/templates/app/store/storeDetail-purchase.html, src/main/resources/templates/app/store/storeList.html
=> [추성윤] 경로 및 QR 주소 수정

src/main/java/com/app/neos/controller/chatting/ChatRestController.java, src/main/java/com/app/neos/controller/handler/WebSocketHandler.java, src/main/java/com/app/neos/domain/chatting/ChattingRoomDTO.java, src/main/java/com/app/neos/entity/chatting/ChattingContent.java, src/main/java/com/app/neos/entity/chatting/ChattingRoom.java, src/main/java/com/app/neos/service/fix/FixService.java, src/main/resources/static/js/fix/chattingAll.js, src/main/resources/static/js/main/main.js, src/main/resources/templates/app/fix/chattingAll.html, src/main/resources/templates/app/main/main.html, src/test/java/com/app/neos/entity/chatting/ChattingRoomEntityTest.java, src/test/java/com/app/neos/service/fix/FixServiceTest.java
채팅방 삭제 완료(무결성 제약 조건 확인중) / 채팅방 만들기 90% 완료
=> 조성현 - 채팅방 삭제 완료(무결성 제약 조건 확인중) / 채팅방 만들기 90% 완료

src/main/java/com/app/neos/controller/store/StoreController.java, src/main/resources/static/css/store/storeDetail.css, src/main/resources/static/js/store/storeDetail.js, src/main/resources/static/js/store/storeModal.js, src/main/resources/templates/app/store/storeDetail-free.html, src/main/resources/templates/app/store/storeDetail-pay.html, src/main/resources/templates/app/store/storeDetail-purchase.html
=> [추성윤] 자료상점 유효성 검사 및 편의성 모달 추가

src/main/java/com/app/neos/controller/community/CommunityController.java, src/main/java/com/app/neos/controller/community/CommunityRestController.java, src/main/java/com/app/neos/controller/main/MainController.java, src/main/java/com/app/neos/domain/community/CommunityDTO.java, src/main/java/com/app/neos/entity/community/Community.java, src/main/java/com/app/neos/entity/community/CommunityLike.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepository.java, src/main/java/com/app/neos/repository/community/CommunityCustomRepositoryImpl.java, src/main/java/com/app/neos/repository/community/CommunityLikeCustomRepository.java, src/main/java/com/app/neos/repository/community/CommunityLikeCustomRepositoryImpl.java, src/main/java/com/app/neos/service/community/CommunityService.java, src/main/java/com/app/neos/service/main/MainService.java, src/main/resources/static/css/community/board3.css, src/main/resources/static/css/fix/loginHeader.css, src/main/resources/static/js/community/freeBoardAjax.js, src/main/resources/static/js/community/freeboard.js, src/main/resources/templates/app/community/freeboard.html, src/test/java/com/app/neos/service/community/CommunityServiceTest.java
[김로사] - 커뮤니티 자유게시판 좋아요 완료, 버그 수정
=> [김로사] - 커뮤니티 자유게시판 좋아요 완료, 버그 수정

src/main/java/com/app/neos/controller/main/MainController.java, src/main/java/com/app/neos/repository/neos/MainBannerCustomRepository.java, src/main/java/com/app/neos/repository/neos/MainBannerCustomRepositoryImpl.java, src/main/java/com/app/neos/service/main/MainService.java, src/main/resources/templates/app/main/main.html
=> 심민성 배너 최종 완료

src/main/resources/templates/app/myPage/my.html
=> [추성윤] 네오력 등급업 설명 추가

src/main/resources/static/js/store/storeModal.js, src/main/resources/templates/app/store/storeDetail-pay.html
[추성윤] 결제 직접입력의 경우 자료상점 결제 오류 수정
=> [추성윤] 결제 직접입력의 경우 자료상점 결제 오류 수정
